services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      KVM: /dev/kvm
      USERNAME: "Sadood"
      PASSWORD: "changeme"
    volumes:
      - /workspaces/windows/win11:/storage
      - /workspaces/windows/data:/data
    devices:
      - /dev/kvm
#      - /dev/dri
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: unless-stopped
